### ISSUE TITLE
Unable to locate com.hashnot.u.async.executor.Executor2 class

### ISSUE THREAD

**Issue by rougeSE** [rafalkrupinski/etsy#2]
The services portion of the Etsy SDK is making use of the com.hashnot.u.async.executor.Executor2 that is not included ad part of the maven dependencies.

 Where can I locate this class?

**Comment by rafalkrupinski** [comment]
Hi,

check here: https://github.com/rafalkrupinski/micro

I don't develop or support this projects and service package is over-engineered. In case of difficulties when using it, I'd suggest using the interfaces and rescu directly.

Also note Etsy changes it's API evenry now and then without notice, so some functions or DTO mappings may be out of sync.

Good luck.

**Comment by rougeSE** [comment]
As an engineer myself I love things that are "over-engineered". I appreciate just having something to look at as the JAX-RS is all new to me, so thank you for posting.

I have your micro repository but there is no package called com.hashnot.u.async.executors in the micro-async. Any chance you have a missing commit in micro that has this class?

**Comment by rafalkrupinski** [comment]
Sorry, I don't have that projects working directory on my laptop.

The API is the JAX-RS code, just create a proxy object with rescu and you're ready to go.

All you'd get from the .service package is handling the results pagination and lot's of overhead from threading and RxJava.

**Comment by rafalkrupinski** [comment]
I just removed the .service package and added an example call in src/main/test.
Have fun!

**Comment by rougeSE** [comment]
Thank you so much for the example! I was not aware of the rescu proxy, so much simpler then what I was trying to do with the core JAX-RS API.

Had to make one minor update to the example to work, but it worked like a champ. Submitted a pull request to fix and expanded on your example.

Can't tell you how much I appreciate your help.

**Comment by rafalkrupinski** [comment]
Glad to hear it. Thanks for improving the examples!
